<?php

function formmodule_theme($existing, $type, $theme, $path) {

  return [
    'formmoduletheme' => [
//        'variables' =>
//           [
//               'templatefields' => NULL,
//               'form' => NULL
//           ],
        'render element' => 'form',
        'template' => 'my-formmodule-name',
    ],
  ];
    
    
//    return array(
//        'formbuildtheme' => array(
//           'variables' =>
//                [
//                    'templatefields' => NULL,
//                    'form' => NULL
//                ],
//            'template' => 'my-formbuild-name',
//            'render element' => 'form'
//        ),
//    );    
}
